### ISSUE TITLE
need to manually install two packages

### ISSUE THREAD

**Issue by wimdecorte** [soliantconsulting/fm-data-api-client#8]
Using node.js 12.22.9 on both windows and debian 10: when I clone a repo that uses fm-data-api-client a "module missing" error is thrown about node-fetch.  Manually installing node-fetch does not fix the issue, I have to install it with a specific version.

I find that I need to run these to npm install commands to make it work:
npm install node-fetch@^2.6.0
npm install @js-joda/core@^3.0.0

(which is pretty old version of node fetch).
Any ideas why the proper packages seem to get installed on the machine where fm-data-api-client is installed manually but do not get added when running 'npm install' on other machines after a git clone?

**Comment by DASPRiD** [comment]
node-fetch is a peer dependency (same with @js-joda/core, although that one is technically optional). We are still relying on node-fetch v2 because there are TypeScript resolution issues with v3(due to v3 using ESM, which is still rather experimental)  the last time I checked, and the general consensus in the bug ticket was to use v2 until it's resolved.

See https://github.com/node-fetch/node-fetch/issues/1263

**Comment by DASPRiD** [comment]
`node-fetch` was made a standard dependency in version 1.2.0. The `@js-joda/core` requirement is still present but `DateUtil` has been marked deprecated, and we will remove that peer dependency in version 2.0.
